import Head from 'next/head';
import Footer from '../components/Footer/footer';
import Navbar from '../components/Navbar/navbar';
import Banner from '../components/Banner/banner';
//import Cards from '../components/Cards/cards';

export default function Home(data) {
	return (
		<div className="max-w-[1440px] m-auto realative font-PlusJakartaSans relative">
			<Head>
				<title>Frontend Mentor | Skilled e-learning landing page</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" sizes="32x32" href="./assets/favicon-32x32.png" />
			</Head>
			<Navbar />
			<img
				src="/assets/image-hero-desktop.png"
				className="absolute lg:top-[-150px] lg:right-[-350px] lg:inline hidden md:hidden"
			/>
			<img
				src="/assets/image-hero-tablet.png"
				className="absolute hidden md:inline lg:hidden md:top-[-100px] md:right-[-300px] "
			/>

			<Banner />

			<Footer />
		</div>
	);
}

export async function getStaticProps() {
	const host = process.env.HOST;
	const res = await fetch('https://skilled-e-learning-landing-page1.vercel.app/api/data');
	const data = await res.json();
	return {
		props: {
			data
		}
	};
}
